[package]
name = "configur"
version = "0.1.0"
edition = "2021"

[dependencies]
camino = "1.1.6"
clap = { version = "4.3.23", features = ["derive"] }
glob = "0.3.1"
serde_json = "1.0.105"
serde_yaml = "0.9.25"
